package aac_bpo_services;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import BPO_system.mysqlConnection;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author akila
 */
public class filteredListForm extends javax.swing.JFrame {
    String p_id;
    String s_id_selected;
    String c_id;
    int cost;
    /**
     * Creates new form filteredListForm
     */
    
    public filteredListForm() {
        initComponents();  
    }
    
    public filteredListForm(String p_id,String c_id) {
        initComponents();
        this.p_id = p_id;   
        this.c_id = c_id;
        bindListTable();
        btnNegotiate.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilteredList = new javax.swing.JTable();
        btnNegotiate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblFilteredList.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        tblFilteredList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFilteredList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilteredListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFilteredList);

        btnNegotiate.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnNegotiate.setText("Negotiate");
        btnNegotiate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegotiateActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNegotiate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNegotiate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNegotiateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegotiateActionPerformed
        JOptionPane.showMessageDialog(null, "Negotiation Initiated");
         try{
            int total_n = 0;
            mysqlConnection con = new mysqlConnection();
            ResultSet rs=con.mysqlConnectionQuery("SELECT COUNT(*) from Negotiation");
            while(rs.next())
                  total_n=rs.getInt(1);
            int temp = 101 + total_n;
            String neg_id = "N" + temp;
            String sql = String.format("INSERT INTO Negotiation VALUES('%s', '%s', '%s', '%s', %d)", neg_id, p_id, s_id_selected, "Offer by Client", cost);
            con.mysqlConnectionUpdate(sql);    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
//        ClientDashboard cd = new ClientDashboard(c_id);
//        cd.setVisible(true);
//        dispose();
    }//GEN-LAST:event_btnNegotiateActionPerformed

    private void tblFilteredListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilteredListMouseClicked
        int rowNum = tblFilteredList.getSelectedRow();
        s_id_selected = (String)tblFilteredList.getValueAt(rowNum, 0);
        cost = (int)tblFilteredList.getValueAt(rowNum, 4);
        btnNegotiate.setEnabled(true);
    }//GEN-LAST:event_tblFilteredListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ViewProcesses redirect=new ViewProcesses(c_id);
this.setVisible(false);
redirect.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filteredListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filteredListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filteredListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filteredListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filteredListForm().setVisible(true);
            }
        });
    }

    private void bindListTable(){
        try{
            String sql = "SELECT s.s_id as ID, sp_name as Company_Name, s_domain as Domain, s_no_of_emp as Employees, cost as Cost " +
                        "FROM Client c, Process p, Service s, Service_Provider sp " +
                        "WHERE c.c_id = p.c_id " +
                        "    AND s.sp_id = sp.sp_id " +
                        "    AND s.status = 'not assigned' " +
                        "    AND p_domain = s_domain " +
                        "    AND p_no_of_emp <= s_no_of_emp " +
                        "    AND cost BETWEEN min_cost AND max_cost "+
                        "    AND p_id = '" + p_id + "'";
            mysqlConnection con = new mysqlConnection();
            ResultSet rs = con.mysqlConnectionQuery(sql);
            tblFilteredList.setModel(buildTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();

            vector.add(rs.getObject(1));
            vector.add(rs.getObject(2));
            vector.add(rs.getObject(3));
            vector.add(rs.getObject(4));
            vector.add(rs.getObject(5));

            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNegotiate;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFilteredList;
    // End of variables declaration//GEN-END:variables
}
