/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aac_bpo_services;

import javax.swing.JOptionPane;
import BPO_system.mysqlConnection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class Negotiation_SP extends javax.swing.JFrame {

    /**
     * Creates new form Negotiation_SP
     */
    public Negotiation_SP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Negotiation ID", "Service ID", "Service Name", "Process ID", "Process Name", "Client Name", "Current Bid", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButton1.setText("Accept Offer");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButton2.setText("Renegotiate");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButton3.setText("Cancel Negotiation");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Offers for Services");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(31, 31, 31)
                                .addComponent(jButton4)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String sp_id;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
if(jTable1.getSelectedRow()>=0)
{
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    int row_ind=jTable1.getSelectedRow();
    String status=(String) jTable1.getValueAt(row_ind,7);
    System.out.println(status);
    if(status.equals("Accepted"))
    {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }
    else if(status.equals("Offer by Service"))
    {
         jButton1.setEnabled(false);
         jButton2.setEnabled(false);
    }
    else if(status.equals("completed"))
    {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }
    else if(status.equals("Cancelled by Client") ||status.equals("Cancelled by Provider"))
    {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }
}
else if(jTable1.getSelectedRow()==-1)
{
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
}
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int ans=JOptionPane.showConfirmDialog(this,"Do You want to accept the offer?");
            if(ans==0)
            {
                int row_ind=jTable1.getSelectedRow();
                String neg_id=(String) jTable1.getValueAt(row_ind,0);
                mysqlConnection mysql1=new mysqlConnection();
                mysql1.mysqlConnectionUpdate("Update Negotiation set status=\"Accepted\" where n_id=\""+neg_id+"\"");
                JOptionPane.showMessageDialog(this,"Offer Accepted Negotiation Complete");
            }
        }
        catch(Exception e)
        {System.out.println(e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            mysqlConnection my1=new mysqlConnection();
            String query="select neg.n_id,neg.s_id,ser.s_domain,neg.p_id,pro.p_domain,cl.c_name,neg.net_amt,neg.status from Negotiation neg,Process pro,Service ser,Service_Provider sp,Client cl where neg.p_id=pro.p_id and neg.s_id=ser.s_id and pro.c_id=cl.c_id and ser.sp_id=sp.sp_id and ser.sp_id=\""+sp_id+"\";";
            ResultSet rs1=my1.mysqlConnectionQuery(query);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while(rs1.next())
            {
                String negoid=rs1.getString(1);
                String proid=rs1.getString(2);
                String prodom=rs1.getString(3);
                String serid=rs1.getString(4);
                String serdom=rs1.getString(5);
                String spname=rs1.getString(6);
                int netAmt=rs1.getInt(7);
                String status=rs1.getString(8);
                Object[] row={negoid,proid,prodom,serid,serdom,spname,netAmt,status};
                model.addRow(row);
            }
            jButton1.setEnabled(false);jButton2.setEnabled(false);jButton3.setEnabled(false);
        }
        catch(Exception e)
        {System.out.println(e);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
    int row_ind=jTable1.getSelectedRow();
    String status=(String) jTable1.getValueAt(row_ind,7);
    String neg_id=(String) jTable1.getValueAt(row_ind,0);
    if(status.equals("Accepted"))
    {JOptionPane.showMessageDialog(this,"The Negotiation has been Accepted\n No renegotiation is possible.");}
    else if(status.equals("Cancelled"))
    {JOptionPane.showMessageDialog(this,"The Negotiation has been Cancelled\n No renegotiation is possible.");}
    else
    {
        int new_amt=Integer.parseInt(JOptionPane.showInputDialog(this,"Enter New Offer Amount:"));
        mysqlConnection my2=new mysqlConnection();
        System.out.println(new_amt);
        my2.mysqlConnectionUpdate("UPDATE Negotiation set net_amt="+new_amt+", status=\"Offer by Service\" where n_id=\""+neg_id+"\"");
        JOptionPane.showMessageDialog(this,"New offer has been sent to Client");
    }
}
catch(Exception e)
{System.out.println(e);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            mysqlConnection my1=new mysqlConnection();
            String query="select neg.n_id,neg.s_id,ser.s_domain,neg.p_id,pro.p_domain,cl.c_name,neg.net_amt,neg.status from Negotiation neg,Process pro,Service ser,Service_Provider sp,Client cl where neg.p_id=pro.p_id and neg.s_id=ser.s_id and pro.c_id=cl.c_id and ser.sp_id=sp.sp_id and ser.sp_id=\""+sp_id+"\";";
            ResultSet rs1=my1.mysqlConnectionQuery(query);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while(rs1.next())
            {
                String negoid=rs1.getString(1);
                String proid=rs1.getString(2);
                String prodom=rs1.getString(3);
                String serid=rs1.getString(4);
                String serdom=rs1.getString(5);
                String spname=rs1.getString(6);
                int netAmt=rs1.getInt(7);
                String status=rs1.getString(8);
                Object[] row={negoid,proid,prodom,serid,serdom,spname,netAmt,status};
                model.addRow(row);
            }
            jButton1.setEnabled(false);jButton2.setEnabled(false);jButton3.setEnabled(false);
        }
        catch(Exception e)
        {System.out.println(e);}         // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try{
    int row_ind=jTable1.getSelectedRow();
    String status=(String) jTable1.getValueAt(row_ind,7);
    String neg_id=(String) jTable1.getValueAt(row_ind,0);
    if(status.equals("Accepted"))
    {JOptionPane.showMessageDialog(this,"The Negotiation has been Accepted\n No Cancellation is possible.");}
    else
    {
        mysqlConnection my2=new mysqlConnection();
        my2.mysqlConnectionUpdate("UPDATE Negotiation set net_amt= 0, status=\"Cancelled by Provider\"where n_id=\""+neg_id+"\"");
        JOptionPane.showMessageDialog(this,"Offer has been Canclled");
    }
}
catch(Exception e)
{System.out.println(e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  ServiceProviderDashboard spd = new ServiceProviderDashboard(sp_id);
            spd.setVisible(true);
            dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Negotiation_SP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Negotiation_SP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Negotiation_SP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Negotiation_SP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Negotiation_SP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
